-- 报关-终端报文信息表 @author Zeyee --
DROP TABLE IF EXISTS apply_terminal;
CREATE TABLE apply_terminal
(
created_by BIGINT(20) NOT NULL COMMENT '创建人',
created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
updated_by BIGINT(20) NOT NULL  COMMENT '修改人',
updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
ver VARCHAR(3) NOT NULL COMMENT '版本',
teminal_id VARCHAR(32) NOT NULL COMMENT '唯一编码',
trans_post_id VARCHAR(32) NOT NULL COMMENT '传输报文id',
id BIGINT(20) AUTO_INCREMENT NOT NULL COMMENT '主键id,自增',
PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='报关-终端报文表';
-- end --

-- 报关-传输报文信息表 @author Zeyee --
DROP TABLE IF EXISTS apply_transport;
CREATE TABLE apply_transport
(
created_by BIGINT(20) NOT NULL COMMENT'创建人',
created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT'创建时间',
updated_by BIGINT(20) NOT NULL COMMENT'修改人',
updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT'修改时间',
ver VARCHAR(3) NOT NULL COMMENT '版本',
transpost_id VARCHAR(32) NOT NULL COMMENT '唯一编码',
id BIGINT(32) AUTO_INCREMENT NOT NULL COMMENT '主键id,自增',
PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='报关-传输报文表';
-- end --