server:
    port: 8088
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:  #数据源1
                url: jdbc:mysql://127.0.0.1:3306/imports?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&&autoReconnect=true&failOverReadOnly=false
                username: root
                password: root
            second:  #数据源2
                url: jdbc:mysql://127.0.0.1:3306/imports?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&&autoReconnect=true&failOverReadOnly=false
                username: root
                password: root
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

# 文件上传
fileupload:
    server: http://localhost:8080/fileupload
    filepath: d:/file
#监控目录
filterdir:
    path: E://testjinchukou/temp/DXPEDCCEB0000003/
    remotelyPath: \\10.0.31.107\receive\DXPEDCCEB0000003
    #不是回执报文拷贝目录，没有监控
    copyPatch: E://testjinchukou/temp/回执报文存储
    #发送报文路径
    sendPath: E://testjinchukou/send/
ueditor:
    imageActionName: uploadimage
    imageUrlPrefix: http://localhost:8080/fileupload
    imagePath: /fileupload/
    imageFieldName: upfile
    imageMaxSize: 2048
# 日志
logback:
    logdir: E://wzlue-logs/wzlue-imports-web
    appname: wzlue-web
    logCount: 10000 #日志阈值
#ftp config
FTP:
    enabled: true
    host: 10.0.31.107
    port: 996
    username: root
    password: root
    changeWorkingDirectory: C://file